import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchData } from "./toolAPI";

const initialState = {
  value: 0,
  status: "idle",
  data: [],
};

export const initalDataAsync = createAsyncThunk(
  "tool/fetchData",
  async (amount) => {
    const response = await fetchData();
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);
export const initalDataSlice = createSlice({
  name: "tool",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(initalDataAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(initalDataAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.data = action.payload;
      });
  },
});

export const { incrementByAmount } = initalDataSlice.actions;

export const selectPartialState = (part) => (state) => {
  return state.tool[part];
};


export default initalDataSlice.reducer;